### ISSUE TITLE
알람 테스트의 경우 이벤트가 호출되지 않나요?

### ISSUE THREAD

**Issue by noonmaru** [patrick-mc/twipe#1]
제 Twipe 보다 구현이 우아해서 테스트 해보고 있는데 테스트 후원에 이벤트가 호출되지 않습니다.

config 설정은 다음과 같습니다.

```yaml
twip-version: 1.1.59
keys:
  Heptagram: https://twip.kr/widgets/alertbox/xxxxxxxxx
```

혹시 진짜 후원만 이벤트를 호출하나요?
