### ISSUE TITLE
테스트 후원

### ISSUE THREAD

**Issue by jini5012** [patrick-mc/twipe#2]
이거 테스트 후원 설정과 테스트 후원을 어떻게 하나요?

**Comment by playerdecuple** [comment]
**Config.yml은 `[플러그인 폴더 (twipe)]\src\main\resources\`에 있습니다.**

[Config.yml](https://github.com/patrick-mc/twipe/blob/master/src/main/resources/config.yml)의 주석을 보면 keys에 스트리머 이름과 트윕(Alert box)의 고유 키를 넣으라고 씌여 있습니다.

아래와 같은 형식이 되도록 만들겠습니다.
```yml
twip-version: 1.1.59
keys:
  [스트리머 이름]: [트윕 Alert Box 고유 키]
```

스트리머 이름은 `https://www.twitch.tv/[스트리머 ID]`의 `[스트리머 ID]` 부분을 쓰면 됩니다.
그리고 Keys의 key 부분을 구하려면

1. [트윕 대시보드 Alert Box 메뉴](https://twip.kr/dashboard/alertbox)에 접속해 줍니다.
2. 고유 URL 주소가 가려져 있을 겁니다. 클릭하면 열립니다.
![image](https://user-images.githubusercontent.com/64447484/99901198-29d0e680-2cf8-11eb-8141-cd6bac8754b4.png)
3. 붉은 색으로 가려져 있는 곳에 문자열 조합이 있을 겁니다. 복사해 줍니다.
4. Key를 얻었습니다.

이제 config.yml에 기입해 줍니다.
예를 들어 스트리머 이름이 ABCD이고 트윕 Alert Box 키가 AaBbCc라고 한다면

```yml
twip-version: 1.1.59
keys:
  ABCD: AaBbCc
```
이렇게 수정해 줍니다. (또는 기입합니다.)
이제 마인크래프트 서버에 플러그인을 적용하고, 서버를 켜 주시면 적용됩니다.

테스트 후원은 아래와 같이, Alert Box 메뉴에서 `알람 테스트` 버튼을 클릭 후 `후원 테스트`를 클릭해 주면 됩니다.
![image](https://user-images.githubusercontent.com/64447484/99901293-fa6ea980-2cf8-11eb-9955-1b6052a8c10f.png)
